on:
  push:
    branches: [main]

jobs:
  sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout com submódulos
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"

      - name: Verifica quais submódulos foram modificados
        id: changed
        run: |
          git submodule foreach 'git fetch origin && git status'
          git diff --cached --submodule=log > submodule_changes.txt
          cat submodule_changes.txt

          changed_submodules=$(git diff --cached --submodule=log | grep "Submodule" | awk '{print $2}')
          echo "changed_submodules=$changed_submodules" >> $GITHUB_ENV

      - name: Propaga alterações de volta aos submódulos
        if: env.changed_submodules != ''
        run: |
          for module in ${{ env.changed_submodules }}; do
            echo "Propagando alterações para $module"
            cd "$module"

            git push origin HEAD:main || echo "Falha ao fazer push em $module (pode estar em detached HEAD)"
            cd -
          done
