name: 🔄 Sync Bidirectional Submodules

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent + submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name  "GitHub Actions Bot"
          git config user.email "actions@github.com"
          # Faz com que todo git push no parent também envie commits pendentes nos submodules
          git config push.recurseSubmodules on-demand

      - name: Commit & push changes
        run: |
          # (opcional) se quiser commitar alterações nos submodules: 
          git submodule foreach --quiet '
            if [[ -n "$(git status --porcelain)" ]]; then
              git checkout main
              git add .
              git diff --cached --quiet || git commit -m "🔄 Sync from parent @${GITHUB_SHA:0:7}"
            fi
          '
          # Agora commit no parent (poderá incluir nova referência de submodule)
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔄 Parent changes (incluindo submodules)"
            git push origin main
          fi
